language: java
sudo: required

services:
  - docker

addons:
  sonarcloud:
    organization: "twasi"

jobs:
  include:
    - stage: tests
        - "mvn surefire:test sonar:sonar"
    - stage: build
      script:
        - "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn clean compile sonar:sonar assembly:single docker:build"
    - stage: deploy
      script:
        - "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn clean compile sonar:sonar assembly:single docker:build -DpushImage"

stages:
  - tests
  - build
  - name: deploy
    if: branch = master

